### ISSUE TITLE
How do we use graph algorithm to plan trajectories.

### ISSUE THREAD

**Issue by a-b-h-i-j-e-e-t** [akhilesh-k/PythonRobotics#3]
I am sorry but the repository says it contains work on Path planning and I am newbie here so how can I work with path planning algorithm.

**Comment by akhilesh-k** [comment]
This is a continuous process. The plan is to add algorithms everyday and due to some issues I was unable to do so.
It will see some contributions soon on path planning. For now if you wish you can check out work on A* and Dijikstra algorithm implemented in MATLAB [here](https://github.com/akhilesh-k/Robotics-Specialization/tree/master/ComputationalMotionPlanning/Assignment%201).
Welcome to the world of Robotics.

**Comment by a-b-h-i-j-e-e-t** [comment]
I am able to find the algorithm but I wish soon implementation be added in Python.

**Comment by akhilesh-k** [comment]
Sure it will, keep tuned~
